version: '3'

services:
  golangci-lint-runner:
    build: .
    environment:
      - HOST_ADDR=:8000
      - GITHUB_PRIVATE_KEY=/path/to/github-app/private-key
      - GITHUB_WEBHOOK_SECRET=SECRET-THAT-YOU-SPECIFIED-IN-THE-APP
      - GITHUB_APP_ID=GUTHUB-APPID