steps:
  - label: ":building_construction: :docker: Build Container"
    concurrency: 1
    concurrency_group: "golangci-lint-runner/push-container"
    plugins:
      docker-compose#v3.0.3:
        config: docker-compose.yml
        build: golangci-lint-runner
        image-name: ${BUILDKITE_COMMIT}
        image-repository: eu.gcr.io/talon-farm2/talon-one/golangci-lint-runner/${BUILDKITE_BRANCH}

  - wait

  - label: ":arrow_up: :docker: Pushing Container"
    concurrency: 1
    concurrency_group: "golangci-lint-runner/push-container"
    plugins:
      docker-compose#v3.0.3:
        config: docker-compose.yml
        push:
          docker-go-node:eu.gcr.io/talon-farm2/talon-one/golangci-lint-runner/${BUILDKITE_BRANCH}:latest