apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: golangci-lint-runner
  name: golangci-lint-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golangci-lint-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: golangci-lint-runner
    spec:
      containers:
      - name: golangci-lint-runner
        image: eu.gcr.io/talon-farm2/talon-one/golangci-lint-runner/master:69708abd76d45c0b8f9d7c67f551c3c109f1676c
        imagePullPolicy: Always
        env:
        - name: HOST_ADDR
          value: ":8000"
        - name: GITHUB_PRIVATE_KEY
          value: "/etc/secrets/private-key"
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: GITHUB_APP_ID
              name: golangci-lint-runner
        - name: GITHUB_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: GITHUB_WEBHOOK_SECRET
              name: golangci-lint-runner
        - name: DEBUG
          value: "true"
        volumeMounts:
          - name: privatekey
            mountPath: "/etc/secrets"
            readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 8000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: privatekey
          secret:
            secretName: golangci-lint-runner
            items:
              - key: GITHUB_PRIVATE_KEY
                path: private-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: golangci-lint-runner
  name: golangci-lint-runner
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: golangci-lint-runner
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: golangci-lint-runner
    hostname: golangci.talon.farm
  name: golangci-lint-runner
spec:
  rules:
  - host: golangci.talon.farm
    http:
      paths:
      - backend:
          serviceName: golangci-lint-runner
          servicePort: 80
---
apiVersion: v1
data:
  GITHUB_APP_ID: MTIzNDU=
  GITHUB_WEBHOOK_SECRET: c2VjcmV0
  GITHUB_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQouLi4KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: golangci-lint-runner
type: Opaque

